### ISSUE TITLE
How can i generate token refresh ? 

### ISSUE THREAD

**Issue by RedRosh** [cnohall/node-google-ads-api#1]
sorry to bother you , but i could not generate the refresh token , can you please show me ( resources ... ) so that i do so .

**Comment by cnohall** [comment]
Hello RedRosh, 

It's quite tricky, but you can learn more by reading the [google docs](https://developers.google.com/identity/protocols/oauth2/javascript-implicit-flow).

**Comment by RedRosh** [comment]
Hi again , i read the the doc but i could not link the google-ads-api and the instructions in docs . sorry i know  my questions are silly but am new to google ads api .
